DROP TABLE Users IF EXISTS;
DROP TABLE Song IF EXISTS;
DROP TABLE Artist IF EXISTS;
DROP TABLE SONGPLAY IF EXISTS;
DROP TABLE PLAYLIST IF EXISTS;
DROP TABLE ALBUM IF EXISTS;
DROP TABLE PUBLISHER IF EXISTS;
