insert into Artist (name, location, join_date, admin, publisher) values ('Brear', 'Brazil', '3/1/2022', true, 'Marks-Durgan');
insert into Artist (name, location, join_date, admin, publisher) values ('Lorry', 'China', '4/9/2022', true, 'Kirlin, Schmidt and Rippin');
insert into Artist (name, location, join_date, admin, publisher) values ('Sunny', 'Canada', '1/7/2022', false, 'Bergnaum, Crona and Mills');
insert into Artist (name, location, join_date, admin, publisher) values ('Noami', 'Indonesia', '5/6/2022', true, 'Labadie, Lubowitz and Hilpert');
insert into Artist (name, location, join_date, admin, publisher) values ('Krispin', 'Brazil', '12/17/2021', true, 'Sanford-Ward');
insert into Artist (name, location, join_date, admin, publisher) values ('Emmery', 'China', '6/14/2022', true, 'Baumbach, Mueller and Howe');
insert into Artist (name, location, join_date, admin, publisher) values ('Yehudi', 'Mexico', '5/6/2022', false, 'Casper, Casper and Kuvalis');
insert into Artist (name, location, join_date, admin, publisher) values ('Marylee', 'Indonesia', '11/2/2021', false, 'Kutch-Miller');
insert into Artist (name, location, join_date, admin, publisher) values ('Bevon', 'Ukraine', '2/1/2022', true, 'Keeling, Lang and Connelly');
insert into Artist (name, location, join_date, admin, publisher) values ('Rosy', 'Brazil', '4/3/2022', false, 'Spencer Inc');
insert into Artist (name, location, join_date, admin, publisher) values ('Nicola', 'Madagascar', '8/1/2022', false, 'Hoppe LLC');
insert into Artist (name, location, join_date, admin, publisher) values ('Emmerich', 'Poland', '7/25/2022', true, 'Rau-Greenfelder');
insert into Artist (name, location, join_date, admin, publisher) values ('Dorey', 'Philippines', '3/6/2022', false, 'Hermiston LLC');
insert into Artist (name, location, join_date, admin, publisher) values ('Kirsteni', 'Netherlands', '11/10/2021', false, 'Haley Group');
insert into Artist (name, location, join_date, admin, publisher) values ('Webster', 'Russia', '10/10/2022', false, 'Schmitt Group');
insert into Artist (name, location, join_date, admin, publisher) values ('Bea', 'Thailand', '9/11/2022', true, 'Watsica Inc');
insert into Artist (name, location, join_date, admin, publisher) values ('Bronson', 'Tanzania', '10/24/2022', true, 'Cormier, Leannon and Crist');
insert into Artist (name, location, join_date, admin, publisher) values ('Nickie', 'China', '6/6/2022', false, 'Kling and Sons');
insert into Artist (name, location, join_date, admin, publisher) values ('Margaux', 'China', '10/22/2022', false, 'Stokes, Klein and Schuster');
insert into Artist (name, location, join_date, admin, publisher) values ('Seth', 'Sri Lanka', '6/15/2022', true, 'Keebler Group');
insert into Artist (name, location, join_date, admin, publisher) values ('Don', 'Burkina Faso', '1/19/2022', false, 'Dietrich-Roberts');
insert into Artist (name, location, join_date, admin, publisher) values ('Lauraine', 'Argentina', '1/24/2022', false, 'Jerde, Hessel and Steuber');
insert into Artist (name, location, join_date, admin, publisher) values ('Beryl', 'Poland', '10/19/2022', true, 'Walsh, Kerluke and Ledner');
insert into Artist (name, location, join_date, admin, publisher) values ('Veronika', 'Russia', '11/16/2021', true, 'Hickle, Friesen and Thompson');
insert into Artist (name, location, join_date, admin, publisher) values ('Riobard', 'Thailand', '12/28/2021', false, 'Lueilwitz-Rice');
insert into Artist (name, location, join_date, admin, publisher) values ('Lorraine', 'Portugal', '7/11/2022', false, 'Barrows, Sporer and Cummings');
insert into Artist (name, location, join_date, admin, publisher) values ('Judah', 'Micronesia', '12/4/2021', true, 'Crooks, Aufderhar and Wolf');
insert into Artist (name, location, join_date, admin, publisher) values ('Lauralee', 'China', '6/12/2022', false, 'Schumm, Wintheiser and Sawayn');
insert into Artist (name, location, join_date, admin, publisher) values ('Whitney', 'Sweden', '4/11/2022', false, 'Fritsch, Schmidt and Hyatt');
insert into Artist (name, location, join_date, admin, publisher) values ('Angelina', 'Brazil', '8/28/2022', false, 'Emard-Schamberger');
insert into Artist (name, location, join_date, admin, publisher) values ('Malva', 'Indonesia', '12/28/2021', false, 'Waelchi-Brakus');
insert into Artist (name, location, join_date, admin, publisher) values ('Redford', 'Vietnam', '12/4/2021', false, 'Hickle Inc');
insert into Artist (name, location, join_date, admin, publisher) values ('Magdalen', 'Indonesia', '7/28/2022', false, 'McDermott and Sons');
insert into Artist (name, location, join_date, admin, publisher) values ('Bar', 'Albania', '2/25/2022', false, 'Gutkowski LLC');
insert into Artist (name, location, join_date, admin, publisher) values ('Cassey', 'Poland', '1/15/2022', true, 'Hirthe Group');
insert into Artist (name, location, join_date, admin, publisher) values ('Mae', 'Comoros', '6/11/2022', false, 'Fay and Sons');
insert into Artist (name, location, join_date, admin, publisher) values ('Pansy', 'Paraguay', '8/31/2022', false, 'Breitenberg-Reinger');
insert into Artist (name, location, join_date, admin, publisher) values ('Tamra', 'Indonesia', '3/30/2022', true, 'McKenzie Inc');
insert into Artist (name, location, join_date, admin, publisher) values ('Dorisa', 'China', '9/12/2022', true, 'Greenfelder, Williamson and Lubowitz');
insert into Artist (name, location, join_date, admin, publisher) values ('Lawton', 'Poland', '7/2/2022', false, 'Ziemann-Orn');
insert into Artist (name, location, join_date, admin, publisher) values ('Iorgo', 'Luxembourg', '4/6/2022', false, 'Anderson, Smith and Windler');
insert into Artist (name, location, join_date, admin, publisher) values ('Annette', 'Brazil', '9/7/2022', false, 'Langosh, Hahn and Stark');
insert into Artist (name, location, join_date, admin, publisher) values ('Adrienne', 'Yemen', '8/30/2022', true, 'Brekke Inc');
insert into Artist (name, location, join_date, admin, publisher) values ('Crawford', 'China', '2/15/2022', true, 'Shields, Stiedemann and Hegmann');
insert into Artist (name, location, join_date, admin, publisher) values ('Linnell', 'Colombia', '1/29/2022', false, 'Reynolds, Smith and Kris');
insert into Artist (name, location, join_date, admin, publisher) values ('Gregor', 'Philippines', '8/6/2022', true, 'Doyle and Sons');
insert into Artist (name, location, join_date, admin, publisher) values ('Gael', 'Brazil', '10/19/2022', false, 'Rolfson LLC');
insert into Artist (name, location, join_date, admin, publisher) values ('Penny', 'Philippines', '4/22/2022', true, 'Weimann, Zieme and Reilly');
insert into Artist (name, location, join_date, admin, publisher) values ('Hendrika', 'Nigeria', '9/24/2022', false, 'Schimmel, Tromp and Windler');
insert into Artist (name, location, join_date, admin, publisher) values ('Yoko', 'Russia', '11/30/2021', true, 'Sanford-Koelpin');