insert into Artist (artist_id, name, location, join_date) values (1, 'Robust', 'Cairima', '1973-06-21');
insert into Artist (artist_id, name, location, join_date) values (2, 'value-added', 'Krajan Tambakrejo', '2015-08-29');
insert into Artist (artist_id, name, location, join_date) values (3, 'Object-based', 'Sitangkai', '1996-11-30');
insert into Artist (artist_id, name, location, join_date) values (4, 'knowledge user', 'Lyon', '1975-06-16');
insert into Artist (artist_id, name, location, join_date) values (5, 'transitional', 'Barra do Piraí', '1972-01-06');
insert into Artist (artist_id, name, location, join_date) values (6, 'local area network', 'Zolotyy Potik', '1979-06-30');
insert into Artist (artist_id, name, location, join_date) values (7, 'intermediate', 'Mikulcice', '2003-11-04');
insert into Artist (artist_id, name, location, join_date) values (8, 'artificial intelligence', 'Huangmei', '1979-04-10');
insert into Artist (artist_id, name, location, join_date) values (9, 'Cross-group', 'Utrecht (stad)', '1992-10-05');
insert into Artist (artist_id, name, location, join_date) values (10, 'Re-contextualized', 'Rybno', '1989-09-01');
insert into Artist (artist_id, name, location, join_date) values (11, 'fresh-thinking', 'Pampierstad', '1990-06-14');
insert into Artist (artist_id, name, location, join_date) values (12, 'implementation', 'Szombathely', '1995-01-27');
insert into Artist (artist_id, name, location, join_date) values (13, '4th generation', 'Khóra', '1995-06-29');
insert into Artist (artist_id, name, location, join_date) values (14, 'fault-tolerant', 'Nowshahr', '1977-08-21');
insert into Artist (artist_id, name, location, join_date) values (15, 'neural-net', 'Düsseldorf', '1972-01-15');
insert into Artist (artist_id, name, location, join_date) values (16, 'success', 'Matozinhos', '2004-04-29');
insert into Artist (artist_id, name, location, join_date) values (17, 'bi-directional', 'Palapye', '1971-12-17');
insert into Artist (artist_id, name, location, join_date) values (18, 'encryption', 'Buhe', '2014-02-13');
insert into Artist (artist_id, name, location, join_date) values (19, 'object-oriented', 'Hanam', '1997-10-16');
insert into Artist (artist_id, name, location, join_date) values (20, 'global', 'Gorzkowice', '1973-12-08');
insert into Artist (artist_id, name, location, join_date) values (21, 'content-based', 'Panambi', '1982-04-26');
insert into Artist (artist_id, name, location, join_date) values (22, 'Versatile', 'Goussainville', '2006-09-06');
insert into Artist (artist_id, name, location, join_date) values (23, 'homogeneous', 'Stende', '1968-04-26');
insert into Artist (artist_id, name, location, join_date) values (24, 'tangible', 'Soisy-sous-Montmorency', '1981-03-31');
insert into Artist (artist_id, name, location, join_date) values (25, 'pricing structure', 'Jieshou', '1963-11-22');
insert into Artist (artist_id, name, location, join_date) values (26, 'system engine', 'Boca Raton', '2001-01-09');
insert into Artist (artist_id, name, location, join_date) values (27, 'discrete', 'Schellenberg', '2000-02-22');
insert into Artist (artist_id, name, location, join_date) values (28, 'installation', 'Aktsyabrski', '1963-07-15');
insert into Artist (artist_id, name, location, join_date) values (29, 'stable', 'Biloxi', '2018-01-27');
insert into Artist (artist_id, name, location, join_date) values (30, 'Monitored', 'Naxos', '1966-02-01');
insert into Artist (artist_id, name, location, join_date) values (31, 'Fundamental', 'Carvalhal da Aroeira', '1980-12-05');
insert into Artist (artist_id, name, location, join_date) values (32, 'value-added', 'Berlin', '2009-01-10');
insert into Artist (artist_id, name, location, join_date) values (33, 'concept', 'Kamionka', '2022-04-12');
insert into Artist (artist_id, name, location, join_date) values (34, 'Programmable', 'Taesal-li', '1975-04-13');
insert into Artist (artist_id, name, location, join_date) values (35, 'open architecture', 'Mrozy', '2006-05-30');
insert into Artist (artist_id, name, location, join_date) values (36, 'Extended', 'Oslo', '1988-03-20');
insert into Artist (artist_id, name, location, join_date) values (37, 'open architecture', 'Uglovoye', '2014-06-24');
insert into Artist (artist_id, name, location, join_date) values (38, 'empowering', 'Wanhu', '2013-09-29');
insert into Artist (artist_id, name, location, join_date) values (39, 'scalable', 'Matangpayang', '2018-02-17');
insert into Artist (artist_id, name, location, join_date) values (40, 'static', 'Timeng', '1961-09-12');
insert into Artist (artist_id, name, location, join_date) values (41, 'data-warehouse', 'Banjar Batuaji Kaja', '1994-10-15');
insert into Artist (artist_id, name, location, join_date) values (42, 'Focused', 'Zigong', '2009-07-01');
insert into Artist (artist_id, name, location, join_date) values (43, 'success', 'Nakatsugawa', '2016-07-09');
insert into Artist (artist_id, name, location, join_date) values (44, 'fault-tolerant', 'Tuanshan', '1965-03-03');
insert into Artist (artist_id, name, location, join_date) values (45, 'portal', 'Santa Luzia', '2017-03-23');
insert into Artist (artist_id, name, location, join_date) values (46, 'open architecture', 'Ciracap', '2022-10-16');
insert into Artist (artist_id, name, location, join_date) values (47, 'initiative', 'Sishui', '2010-08-24');
insert into Artist (artist_id, name, location, join_date) values (48, 'core', 'Brive-la-Gaillarde', '1963-04-11');
insert into Artist (artist_id, name, location, join_date) values (49, 'hybrid', 'Marshintsy', '1988-11-24');
insert into Artist (artist_id, name, location, join_date) values (50, 'installation', 'Voskopojë', '1990-12-17');
